version: '3'

tasks:
  syntax:
    cmds:
      - go build ./parking/ && echo "Sintax valid for parking module" || echo "Sintax invalid for parking module"
      - go build ./parking/ && echo "Sintax valid for place module" || echo "Sintax invalid for place module"
    silent: true