version: '3'

tasks:
  syntax:
    desc: Check project syntax.
    cmds:
      - go build ./internal/... && echo "Syntax valid for parking module" || echo "Syntax invalid for parking module"
    silent: true

  test:
    desc: Run project tests.
    cmds: 
      - go test ./internal/...

  installdeps:
    desc: Install project dependencies.
    cmds:
      - go mod download
