version: '3'

tasks:
  syntax:
    desc: Check project syntax.
    cmds:
      - go build ./... && echo "Syntax valid for parking module" || echo "Syntax invalid for parking module"
    silent: true

  test:
    desc: Run project tests.
    cmds:
      - export DB_PASS=siga2021 && go test ./...

  installdeps:
    desc: Install project dependencies.
    cmds:
      - go mod download
