version: '3'

tasks:
  syntax:
    desc: Check project syntax.
    cmds:
      - go build ./internal/... && echo "Sintax valid for parking module" || echo "Sintax invalid for parking module"
    silent: true

  test:
    desc: Run project tests.
    cmds: 
      - go test ./internal/...
