# FROM: https://medium.com/cooking-with-azure/publish-containers-to-github-container-registry-with-github-actions-4e39700ae14c

name: Publish container to GitHub Registry

on:
  push:
    paths:
      - dockerfile.test
      - Taskfile.yml

env:
  IMAGE_NAME_TESTING: testing

jobs:
  # Push image to GitHub Packages.
  ghr_push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build -f dockerfile.test -t $IMAGE_NAME_TESTING .

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image to GitHub Container Registry
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/$IMAGE_NAME_TESTING:latest
          # Change all uppercase to lowercase
          IMAGE_ID=${IMAGE_ID,,}
          echo IMAGE_ID=$IMAGE_ID
          docker tag $IMAGE_NAME_TESTING $IMAGE_ID
          docker push $IMAGE_ID:$VERSION
