# FROM: https://medium.com/cooking-with-azure/publish-containers-to-github-container-registry-with-github-actions-4e39700ae14c

name: Publish container to GitHub Registry

on:
  push:
    paths:
      - dockerfile.test
      - Taskfile.yml

jobs:
  # Push image to GitHub Packages.
  ghr_push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          TAG=ghcr.io/${{ github.repository }}:latest
          docker build -f dockerfile.test -t ${TAG,,} .

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image to GitHub Container Registry
        run: |
          TAG=ghcr.io/${{ github.repository }}:latest
          docker push ${TAG,,}
