name: Test

on:
  push:
    paths:
      - Taskfile.yml
      - internal/*

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x, 1.15.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_USER: siga
          POSTGRES_PASSWORD: siga2021
          POSTGRES_DB: places
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install task
      run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d
    - name: Install dependencies
      run: ./bin/task installdeps
    - name: Run tests
      env:
        DB_PASS: siga2021
      run: ./bin/task test
